export const AMAZON_CASUAL_PURCHASER_THRESHOLD = 1;
export const AMAZON_REGULAR_CUSTOMER_THRESHOLD = 10;
export const AMAZON_HEAVY_USER_THRESHOLD = 50;
export const UBER_OCCASIONAL_RIDER_THRESHOLD = 3;
export const UBER_REGULAR_RIDER_THRESHOLD = 25;
export const UBER_POWER_USER_THRESHOLD = 75;
