graph TB
    %%{init: {"flowchart": {"htmlLabels": false}} }%%
    classDef default line-height:1.5,text-align:left;
    classDef FixFont font-size:11px,top:20px;
    subgraph User
      B(Wallet B)
      subgraph CommitmentCircuit
        CommitmentPublic["`**Public**
          Address: B
          Assertion[n]
          Merkle Root
          Community ID
          Community Nullifier[n]
          *= Hash(Secret, Credential[n].UUID, Community ID)*
          Issuer
          Expiry[n]`"]
        CommitmentPrivate["`**Private**
          Secret
          Credential[n]
          Merkle Path[n]`"]:::FixFont
      end
    end

    subgraph Scorer
      StoredCredential["`**Stored Credential[n]**
          Address: B
          Assertion
          Community ID
          Community Nullifier
          Expiry`"]
      StoredCredential-->Database[(Credential\nStorage)]
      StoredCredential-->Score((Score))
    end

    Score-->B
    CommitmentPublic-->StoredCredential
